// Code generated by MockGen. DO NOT EDIT.
// Source: ./dao/admin_dao.go
//
// Generated by this command:
//
//	mockgen -source ./dao/admin_dao.go -destination ./test/mock/mock_admin_dao.go -package mock_dao
//

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	reflect "reflect"
	model "tomatoBlogDB/model"

	gomock "go.uber.org/mock/gomock"
)

// MockIAdminDao is a mock of IAdminDao interface.
type MockIAdminDao struct {
	ctrl     *gomock.Controller
	recorder *MockIAdminDaoMockRecorder
	isgomock struct{}
}

// MockIAdminDaoMockRecorder is the mock recorder for MockIAdminDao.
type MockIAdminDaoMockRecorder struct {
	mock *MockIAdminDao
}

// NewMockIAdminDao creates a new mock instance.
func NewMockIAdminDao(ctrl *gomock.Controller) *MockIAdminDao {
	mock := &MockIAdminDao{ctrl: ctrl}
	mock.recorder = &MockIAdminDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAdminDao) EXPECT() *MockIAdminDaoMockRecorder {
	return m.recorder
}

// CheckAdminNameExist mocks base method.
func (m *MockIAdminDao) CheckAdminNameExist(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdminNameExist", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckAdminNameExist indicates an expected call of CheckAdminNameExist.
func (mr *MockIAdminDaoMockRecorder) CheckAdminNameExist(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdminNameExist", reflect.TypeOf((*MockIAdminDao)(nil).CheckAdminNameExist), name)
}

// CreateAdmin mocks base method.
func (m *MockIAdminDao) CreateAdmin(user *model.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockIAdminDaoMockRecorder) CreateAdmin(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockIAdminDao)(nil).CreateAdmin), user)
}

// GetAdminByName mocks base method.
func (m *MockIAdminDao) GetAdminByName(name string) (*model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminByName", name)
	ret0, _ := ret[0].(*model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminByName indicates an expected call of GetAdminByName.
func (mr *MockIAdminDaoMockRecorder) GetAdminByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminByName", reflect.TypeOf((*MockIAdminDao)(nil).GetAdminByName), name)
}
