// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/author/{name_or_id}": {
            "get": {
                "tags": [
                    "Author"
                ],
                "summary": "Get author details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author Name or ID",
                        "name": "name_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/authors": {
            "get": {
                "tags": [
                    "Author"
                ],
                "summary": "Get author list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/categories": {
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "Get category list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/category/{name_or_id}": {
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "Get category details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID or Name",
                        "name": "name_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "**业务错误码 (Code) 说明：**\n- ` + "`" + `401003` + "`" + ` - 用户名或密码错误\n- ` + "`" + `401004` + "`" + ` - 该账号已被冻结，禁止登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/post/{slug_or_id}": {
            "get": {
                "description": "** url参数可以为slug或id **",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Get post details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID or Slug",
                        "name": "slug_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "publish successfully\" \"成功",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/posts": {
            "get": {
                "tags": [
                    "Post"
                ],
                "summary": "Get post list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search Keyword",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/private/admin": {
            "post": {
                "description": "** 任意添加admin表【！！非业务】**\n** ---- 业务错误码（Cpde）说明 ---- **\n-401005",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create normal user (writer)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Admin Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。注意：实际返回值为 Code: 20100, Msg: 'create a new Admin successfully'",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/{id}": {
            "delete": {
                "description": "only allow supreme admin(Role=999) do this.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete an admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。实际返回值为 Msg: 'delete Admin status successfully'",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/{id}/status": {
            "patch": {
                "description": "only allow supreme admin(Role=999) do this. 1--active 2--disabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "update an admin status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "status",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。实际返回值为 Msg: 'update Admin status successfully'}",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admins": {
            "get": {
                "description": "paginate admin. Requires super admin privileges (role=999).",
                "tags": [
                    "Admin"
                ],
                "summary": "Get admin list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved admin list",
                        "schema": {
                            "type": "200"
                        }
                    },
                    "400": {
                        "description": "Invalid URL parameters",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/category": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Post Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryAddReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/private/category/{id}": {
            "delete": {
                "tags": [
                    "Category"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/private/post": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Post Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/private/post/{id}": {
            "put": {
                "tags": [
                    "Post"
                ],
                "summary": "Update a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostUpdateReq"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Post"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/private/post/{id}/status": {
            "patch": {
                "tags": [
                    "Post"
                ],
                "summary": "Change post status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostStatusReq"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.AdminAddReq": {
            "type": "object",
            "required": [
                "email",
                "mobile",
                "name",
                "password",
                "pen_name",
                "role"
            ],
            "properties": {
                "email": {
                    "description": "校验邮箱格式",
                    "type": "string"
                },
                "mobile": {
                    "description": "中国手机号通常11位",
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "pen_name": {
                    "type": "string",
                    "maxLength": 64
                },
                "real_name": {
                    "type": "string",
                    "maxLength": 20
                },
                "role": {
                    "type": "integer",
                    "maximum": 999
                }
            }
        },
        "dto.AdminLoginReq": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.AdminLoginResp": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "admin"
                },
                "token": {
                    "description": "可以顺手加个 example",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1Ni... "
                }
            }
        },
        "dto.AdminStatusReq": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                }
            }
        },
        "dto.CategoryAddReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 128
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                }
            }
        },
        "dto.PostAddReq": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "title"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "keywords": {
                    "type": "string",
                    "maxLength": 255
                },
                "published_at": {
                    "description": "RFC3339 \"published_at\": \"2026-02-27T18:00:00+08:00\"",
                    "type": "string"
                },
                "slug": {
                    "type": "string",
                    "maxLength": 100
                },
                "subtitle": {
                    "type": "string",
                    "maxLength": 150
                },
                "summary": {
                    "type": "string",
                    "maxLength": 255
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.PostStatusReq": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                }
            }
        },
        "dto.PostUpdateReq": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "title"
            ],
            "properties": {
                "category_id": {
                    "description": "分类通常是必填的，即使不改也要传原值",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keywords": {
                    "type": "string",
                    "maxLength": 255
                },
                "slug": {
                    "type": "string",
                    "maxLength": 100
                },
                "status": {
                    "description": "状态 (例如想把已发布改为草稿)",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "subtitle": {
                    "type": "string",
                    "maxLength": 150
                },
                "summary": {
                    "type": "string",
                    "maxLength": 255
                },
                "tags": {
                    "description": "标签 ID 列表 (全量覆盖)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "model.ResponseJson": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "used to indicate error to front-end engineer",
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "description": "message to front-end user",
                    "type": "string"
                },
                "status": {
                    "description": "0 means not set, use default status code",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
