// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/author/{name_or_id}": {
            "get": {
                "description": "根据作者 ID 或名称 (PenName/Username) 获取作者详情。支持灵活查询。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Author"
                ],
                "summary": "Get author details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author Name or ID",
                        "name": "name_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取作者详情成功",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/authors": {
            "get": {
                "description": "分页获取作者列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Author"
                ],
                "summary": "Get author list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page Number (页码，默认 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page Size (每页数量，默认 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取作者列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AuthorListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/categories": {
            "get": {
                "description": "分页获取分类列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get category list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page Number (页码，默认 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page Size (每页数量，默认 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取分类列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.CategoryListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/category/{name_or_id}": {
            "get": {
                "description": "根据分类 ID 或分类名称获取分类详情。支持灵活查询",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get category details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID or Name (分类的 ID 或名称)",
                        "name": "name_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取分类详情成功",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "**业务错误码 (Code) 说明：**\n- ` + "`" + `401003` + "`" + ` - 用户名或密码错误\n- ` + "`" + `401004` + "`" + ` - 该账号已被冻结，禁止登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/post/{slug_or_id}": {
            "get": {
                "description": "** url参数可以为slug或id **",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Get post details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID or Slug",
                        "name": "slug_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/posts": {
            "get": {
                "description": "获取文章列表（支持分页）。\n注意：为了优化传输性能，列表接口返回的 Post 对象不包含 Content (文章正文)。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Get post list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 (默认: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量 (默认: 10, 最大: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search Keyword",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PostListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/author": {
            "post": {
                "description": "** 添加admin表**\n** ---- 业务错误码（Cpde）说明 ---- **\n-401005",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create normal user (author)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Author Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthorAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。注意：实际返回值为 Code: 20100, Msg: 'create a new Author successfully'",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/supreme": {
            "post": {
                "description": "** 任意添加admin表【！！非业务】**\n** ---- 业务错误码（Cpde）说明 ---- **\n-401005",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create admin (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Admin Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。注意：实际返回值为 Code: 20100, Msg: 'create a new Admin successfully'",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/{id}": {
            "delete": {
                "description": "only allow supreme admin(Role=999) do this.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete an admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。实际返回值为 Msg: 'delete Admin status successfully'",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admin/{id}/status": {
            "patch": {
                "description": "only allow supreme admin(Role=999) do this. 1--active 2--disabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "update an admin status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "admin ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "status",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应。实际返回值为 Msg: 'update Admin status successfully'}",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/private/admins": {
            "get": {
                "description": "paginate admin. Requires super admin privileges (role=999).",
                "tags": [
                    "Admin"
                ],
                "summary": "Get admin list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved admin list",
                        "schema": {
                            "type": "200"
                        }
                    },
                    "400": {
                        "description": "Invalid URL parameters",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/category": {
            "post": {
                "description": "创建一个新分类。\n权限要求：仅限系统管理员 (Role=Admin) 可以执行此操作。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Post Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create a new category successfully",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/category/{id}": {
            "delete": {
                "description": "删除指定的分类\n权限要求：通常仅限系统管理员 (Role=Admin) 可以执行此操作。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Delete a category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/common/uploadimg": {
            "post": {
                "description": "统一图片上传接口 (支持 Markdown 编辑器自动上传)",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Upload Image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.ResponseJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UploadImageResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/private/post": {
            "post": {
                "description": "- 可以指定slug，但建议置为空，让程序自动生成\n- published_at: 发布时间,RFC3339格式：\"2006-01-02T15:04:05Z07:00\" 。若留空则默认为当前时间。\n- 后门字段bd_target_author_id,仅当超级管理员时生效",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Post Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "200"
                        }
                    }
                }
            }
        },
        "/api/v1/private/post/{id}": {
            "put": {
                "description": "更新文章内容。支持部分更新（动态 PATCH 逻辑）：前端只需传入需要修改的字段，未传入的字段将保持原样。\n注意：不支持修改文章作者。仅限文章原作者或系统管理员操作。\n- 后门字段bd_target_author_id, bd_Target_published_at仅当超级管理员时生效\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Update a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Info(仅传需要修改的字段)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update successfully",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的文章（注意：此操作为软删除，数据仍在数据库中，只是被标记为已删除）。\n权限要求：仅限文章原作者或系统管理员(Role=Admin)可以执行此操作。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete Post status successfully / 删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        },
        "/api/v1/private/post/{id}/status": {
            "patch": {
                "description": "Update status field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Change post status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update successfully",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseJson"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdminAddReq": {
            "type": "object",
            "required": [
                "email",
                "mobile",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "校验邮箱格式",
                    "type": "string"
                },
                "mobile": {
                    "description": "中国手机号通常11位",
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "real_name": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "dto.AdminLoginReq": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.AdminLoginResp": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "admin"
                },
                "token": {
                    "description": "可以顺手加个 example",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1Ni... "
                }
            }
        },
        "dto.AdminStatusReq": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                }
            }
        },
        "dto.AuthorAddReq": {
            "type": "object",
            "required": [
                "email",
                "mobile",
                "name",
                "password",
                "pen_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "name": {
                    "description": "登录名",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "pen_name": {
                    "description": "独有字段：必须有笔名",
                    "type": "string",
                    "maxLength": 64
                },
                "real_name": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "dto.AuthorListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AuthorSimple"
                    }
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.AuthorSimple": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mobile": {
                    "type": "string"
                },
                "pen_name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "dto.CategoryAddReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 128
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                }
            }
        },
        "dto.CategoryListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CategorySimple"
                    }
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.CategorySimple": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.PostAddReq": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "title"
            ],
            "properties": {
                "bd_target_author_id": {
                    "description": "== supreme admin only",
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string",
                    "maxLength": 50000
                },
                "cover": {
                    "type": "string",
                    "maxLength": 2048
                },
                "keywords": {
                    "type": "string",
                    "maxLength": 255
                },
                "published_at": {
                    "description": "RFC3339 \"published_at\": \"2026-02-27T18:00:00+08:00\"",
                    "type": "string",
                    "maxLength": 30
                },
                "slug": {
                    "type": "string",
                    "maxLength": 100
                },
                "subtitle": {
                    "type": "string",
                    "maxLength": 150
                },
                "summary": {
                    "type": "string",
                    "maxLength": 255
                },
                "tags": {
                    "description": "Tags 是切片，需要双重限制：限制切片元素个数，以及限制每个元素的长度\nmax=10 表示最多 10 个标签\ndive 表示深入到切片内部验证\n后面的 max=30 表示每个标签字符串最多 30 个字符",
                    "type": "array",
                    "maxItems": 10,
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.PostListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PostSimple"
                    }
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.PostSimple": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.AuthorSimple"
                },
                "author_id": {
                    "description": "关联作者 (Belongs To)\n这里的 Admin 对应你之前的 Admin/User 结构体",
                    "type": "integer"
                },
                "category_id": {
                    "description": "关联分类 (Belongs To)\n一篇文章通常属于一个主分类",
                    "type": "integer"
                },
                "category_name": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "description": "视觉相关\n列表页展示的封面图，不是正文里的图w",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keywords": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "read_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "description": "Status Control",
                    "type": "integer"
                },
                "subtitle": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "tags": {
                    "description": "关联标签 (Many To Many)\n一篇文章可以有多个标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.PostStatusReq": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                }
            }
        },
        "dto.PostUpdateReq": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "title"
            ],
            "properties": {
                "bd_Target_published_at": {
                    "type": "string",
                    "maxLength": 30
                },
                "bd_target_author_id": {
                    "description": "== supreme admin only",
                    "type": "integer"
                },
                "category_id": {
                    "description": "分类通常是必填的，即使不改也要传原值",
                    "type": "integer"
                },
                "content": {
                    "type": "string",
                    "maxLength": 50000
                },
                "cover": {
                    "type": "string",
                    "maxLength": 2048
                },
                "id": {
                    "type": "integer"
                },
                "keywords": {
                    "type": "string",
                    "maxLength": 255
                },
                "slug": {
                    "type": "string",
                    "maxLength": 100
                },
                "status": {
                    "description": "状态 (例如想把已发布改为草稿)",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "subtitle": {
                    "type": "string",
                    "maxLength": 150
                },
                "summary": {
                    "type": "string",
                    "maxLength": 255
                },
                "tags": {
                    "description": "标签 ID 列表 (全量覆盖)",
                    "type": "array",
                    "maxItems": 10,
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "dto.UploadImageResp": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "model.ResponseJson": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "used to indicate error to front-end engineer",
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "description": "message to front-end user",
                    "type": "string"
                },
                "status": {
                    "description": "0 means not set, use default status code",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
