basePath: /
definitions:
  dto.AdminAddReq:
    properties:
      email:
        description: 校验邮箱格式
        type: string
      mobile:
        description: 中国手机号通常11位
        type: string
      name:
        maxLength: 20
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
      pen_name:
        type: string
      real_name:
        maxLength: 20
        type: string
      role:
        type: integer
    required:
    - email
    - mobile
    - name
    - password
    - pen_name
    - role
    type: object
  dto.AdminLoginReq:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  dto.AdminStatusReq:
    properties:
      status:
        enum:
        - 1
        - 2
        type: integer
    type: object
  dto.CategoryAddReq:
    properties:
      description:
        maxLength: 128
        type: string
      name:
        maxLength: 128
        type: string
    required:
    - name
    type: object
  dto.PostAddReq:
    properties:
      category_id:
        type: integer
      content:
        type: string
      cover:
        type: string
      keywords:
        maxLength: 255
        type: string
      published_at:
        description: 'RFC3339 "published_at": "2026-02-27T18:00:00+08:00"'
        type: string
      slug:
        maxLength: 100
        type: string
      subtitle:
        maxLength: 150
        type: string
      summary:
        maxLength: 255
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        maxLength: 100
        type: string
    required:
    - category_id
    - content
    - title
    type: object
  dto.PostStatusReq:
    properties:
      id:
        type: integer
      status:
        enum:
        - 0
        - 1
        - 2
        type: integer
    type: object
  dto.PostUpdateReq:
    properties:
      category_id:
        description: 分类通常是必填的，即使不改也要传原值
        type: integer
      content:
        type: string
      cover:
        type: string
      id:
        type: integer
      keywords:
        maxLength: 255
        type: string
      slug:
        maxLength: 100
        type: string
      status:
        description: 状态 (例如想把已发布改为草稿)
        enum:
        - 0
        - 1
        - 2
        type: integer
      subtitle:
        maxLength: 150
        type: string
      summary:
        maxLength: 255
        type: string
      tags:
        description: 标签 ID 列表 (全量覆盖)
        items:
          type: string
        type: array
      title:
        maxLength: 100
        type: string
    required:
    - category_id
    - content
    - title
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a sample server Petstore server.
  version: "1.0"
paths:
  /api/v1/author/{name_or_id}:
    get:
      parameters:
      - description: Author Name or ID
        in: path
        name: name_or_id
        required: true
        type: string
      responses: {}
      summary: Get author details
      tags:
      - Author
  /api/v1/authors:
    get:
      parameters:
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: Page Size
        in: query
        name: page_size
        type: integer
      responses: {}
      summary: Get author list
      tags:
      - Author
  /api/v1/categories:
    get:
      parameters:
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: Page Size
        in: query
        name: page_size
        type: integer
      responses: {}
      summary: Get category list
      tags:
      - Category
  /api/v1/category/{name_or_id}:
    get:
      parameters:
      - description: Post ID or Name
        in: path
        name: name_or_id
        required: true
        type: string
      responses: {}
      summary: Get category details
      tags:
      - Category
  /api/v1/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginReq'
      produces:
      - application/json
      responses: {}
      summary: Login
      tags:
      - Admin
  /api/v1/post/{slug_or_id}:
    get:
      parameters:
      - description: Post ID or Slug
        in: path
        name: slug_or_id
        required: true
        type: string
      responses: {}
      summary: Get post details
      tags:
      - Post
  /api/v1/posts:
    get:
      parameters:
      - description: Page Number
        in: query
        name: page
        type: integer
      - description: Page Size
        in: query
        name: page_size
        type: integer
      - description: Search Keyword
        in: query
        name: keyword
        type: string
      responses: {}
      summary: Get post list
      tags:
      - Post
  /api/v1/private/admin:
    post:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Admin Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminAddReq'
      responses: {}
      summary: Create normal user (writer)
      tags:
      - Admin
  /api/v1/private/admin/{id}/status:
    patch:
      description: only allow supreme admin(Role=999) do this. 1--active 2--disabled.
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: admin or writer ID
        in: path
        name: id
        required: true
        type: integer
      - description: status
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AdminStatusReq'
      responses: {}
      summary: update admin status
      tags:
      - Admin
  /api/v1/private/author/{id}:
    delete:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Delete a post
      tags:
      - Author
  /api/v1/private/category:
    post:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryAddReq'
      responses: {}
      summary: Create a new category
      tags:
      - Category
  /api/v1/private/category/{id}:
    delete:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Delete a post
      tags:
      - Category
  /api/v1/private/post:
    post:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.PostAddReq'
      responses: {}
      summary: Create a new post
      tags:
      - Post
  /api/v1/private/post/{id}:
    delete:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Delete a post
      tags:
      - Post
    put:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.PostUpdateReq'
      responses: {}
      summary: Update a post
      tags:
      - Post
  /api/v1/private/post/{id}/status:
    patch:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Status
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.PostStatusReq'
      responses: {}
      summary: Change post status
      tags:
      - Post
swagger: "2.0"
